### ISSUE TITLE
1.4.0-pre-5: Error 'charmap' codec can't encode character'

### ISSUE THREAD

**Issue by valsamis-d** [Aetopia/NVIDIA-Driver-Downloader#9]
@Aetopia hi,

Downloaded and tested 1.4.0-pre-5 and I'm getting the following error:

```
An error has occured.
> 'charmap' codec can't encode character '\xc3' in position 255969: character maps to <undefined>
```

See screenshot below:

![image](https://user-images.githubusercontent.com/17590539/179912975-afbe0dcc-e95b-4137-8d9d-3f830744cf49.png)

Log: "%TEMP%\nvddl.log":

```
INFO: Namespace: Namespace(help=False, list=False, download=None, extract=None, update=True, studio=False, standard=False, full=False, setup=False, components=[], output='F:\\Temp\\DVALSA~1', flags=[], no_stdout=False)
INFO: Arguments: ['-u']
ERROR: Exception: 'charmap' codec can't encode character '\xc3' in position 255969: character maps to <undefined>
INFO: Exiting...
```

Traceback: "%TEMP%\nvddl_traceback.txt"

```
Traceback (most recent call last):
  File "F:\Temp\DVALSA~1\ONEFIL~2\main.py", line 19, in main
  File "F:\Temp\DVALSA~1\ONEFIL~2\core\cli.py", line 89, in cli
  File "F:\Temp\DVALSA~1\ONEFIL~2\core\cli.py", line 112, in parse
  File "F:\Temp\DVALSA~1\ONEFIL~2\plugins\files.py", line 47, in fetch
  File "encodings\cp1253.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xc3' in position 255969: character maps to <undefined>
```

Dimitrios

**Comment by Aetopia** [comment]
Looks like some encoding error.

**Comment by valsamis-d** [comment]
> Looks like some encoding error.

Could it be something on my side that I need to configure? Please, that it doesn't occur with the previous build.

**Comment by Aetopia** [comment]
No, I needed to enforce a UTF-8 Encoding on the dumped files.

**Comment by valsamis-d** [comment]
@Aetopia this is fixed is pre-6. Another one, though, came up. I will log a new issue. Thank you!
